- django_comments_xtd/conf/defaults.py
- django_comments_xtd/templatetags/comments_xtd.py
- django_comments_xtd/tests/test_templatetags.py
- docs/settings.rst
This setting allows a developer to choose a default markup filter that will be applied to all non-identified comments. The intent of this is to allow comments more like Reddit (for example), where every comment is interpreted as Markdown, even if the comment does not specify its markup filter in the first line with `#!markdown`.
All other normal operation is preserved.
If the setting is None or is not specified in `settings.py`, this change keeps the normal behavior of returning the comment plaintext.
This change does not interfere with the normal operation where a comment identifies its own markup, eg:
#!restructuredtext
...
will be processed as reStructuredText.
Documentation is included, as well as two additional passing tests.
> Add markup fallback filter setting

- django_comments_xtd/models.py
- django_comments_xtd/templatetags/comments_xtd.py
I found that, using Django 1.9, I got the error `XtdCommentManager has no method 'for_model'` if I tried to use the `get_xtdcomment_tree` template tag. Having added that method (copying it from the [CommentManager](https://github.com/django/django-contrib-comments/blob/master/django_comments/managers.py#L6) class of django_comments) I also realized that the use of `urllib.parse` makes the app incompatible with Python 2, as that library was organized differently. I added some logic to figure out which library name to use.
> Fixed bugs so works with Django 1.9 and Python 2.7

- docs/example.rst
Only this step - install requirements via pip - seems to be missing in the example doc.
> Missing step: install requirements

- django_comments_xtd/models.py
- django_comments_xtd/tests/test_views.py
- django_comments_xtd/views.py
This commit removes the `content_object` and `content_type` model instances
from the tmp comment instance so that the generated comment confirmation email
isn't so large. It also repopulates these keys when confirming the link.
Fixes: #51
> Reduce length of generated confirmation emails.

- MANIFEST.in
- django_comments_xtd/locale/fr/LC_MESSAGES/django.po
- django_comments_xtd/locale/fr/LC_MESSAGES/djangojs.po
- django_comments_xtd/static/django_comments_xtd/js/src/commentform.jsx
- django_comments_xtd/templates/comments/flag.html
- django_comments_xtd/templates/django_comments_xtd/dislike.html
- django_comments_xtd/templates/django_comments_xtd/like.html
- example/comp/settings.py
Three independent commits in the PR in order to use the package in French :
- fix the manifest to include locale files : the package on pypi doesn't have the files needed for translations
- change some hard-coded English sentences to be translatable
- add the French translations
> Add French translations

- .gitignore
- django_comments_xtd/api/frontend.py
- django_comments_xtd/api/views.py
- django_comments_xtd/templatetags/comments_xtd.py
- django_comments_xtd/urls.py
- docs/javascript.rst
- docs/webapi.rst
- pyproject.toml
Hi there,
This PR makes `django-comments-xtd` easier to use with existing API-only django projects,
* adds support for non-int based object_pk, for instead when using UUIDs or HashIds as the primary key on a model (closes #112 )
* refactors the commentbox props generation into a separate function so can be used from the webapi for use with rest_framework/API-only backends that don't make use of server-side templates
* adds a pyproject.yaml for use with `poetry` (https://poetry.eustace.io) and new pip environments (PEP 518)
This is quite a invasive change so happy to take feedback / make changes to get it upstreamed! :)
> Support non-int pks and extract commentbox props for use outside template

- .gitignore
- django_comments_xtd/api/frontend.py
- django_comments_xtd/api/views.py
- django_comments_xtd/templatetags/comments_xtd.py
- django_comments_xtd/tests/test_templatetags.py
- django_comments_xtd/utils.py
- django_comments_xtd/views.py
> get rid of SITE_ID (for multiple site installation)

- .travis.yml
- README.rst
- django_comments_xtd/compat.py
- django_comments_xtd/signed.py
- django_comments_xtd/tests/templates/base.html
- example/comp/templates/base.html
- example/comp/templates/django_comments_xtd/base.html
- example/custom/templates/base.html
- example/simple/templates/base.html
- tox.ini
Mostly removing the usage of `django.utils.six` and replacing it with a standalone `six` module.
> Add Django 3.0 compatibility 

- CHANGELOG.md
- django_comments_xtd/api/serializers.py
- django_comments_xtd/tests/test_api_views.py
- django_comments_xtd/tests/test_serializers.py
- django_comments_xtd/tests/utils.py
- docs/webapi.rst
The permission checked was not the correct one. It had to be `django_comments.can_moderate`.
In order to allow non-superusers to moderate, they have to have the `django_comments.can_moderate` permission.
> Closes Issue 171

- CHANGELOG.md
- LICENSE
- django_comments_xtd/api/serializers.py
- django_comments_xtd/signals.py
- django_comments_xtd/tests/apiauth.py
- django_comments_xtd/tests/models.py
- django_comments_xtd/tests/settings.py
- django_comments_xtd/tests/test_serializers.py
- django_comments_xtd/tests/urls.py
- docs/logic.rst
- docs/templates.rst
- docs/webapi.rst
- example/simple/articles/models.py
- example/simple/settings.py
This PR implements a new behaviour in the validate method of `WriteCommentSerializer`, used when posting comments via the web API. The new behaviour consist of a new signal, `should_request_be_authorized`, which must be used along with [Django REST Framework authentication classes](https://www.django-rest-framework.org/api-guide/authentication/) to authorize the request. Implements corresponding regression tests. 
Read the extended documentation about the web API (will be released with v2.7.0).
> Close issue 155

- docs/tutorial.rst
Closes #189 on mentioning the `who_can_post` option in the Tutorial so that the documentation introduces the topic of "allow to post comments only to signed in users" in an earlier stage.
> Update tutorial.rst to mention 'who_can_post' use case. Closes #189.

- .travis.yml
- CHANGELOG.md
- django_comments_xtd/urls.py
- tox.ini
Adds Django 3.1 to the battery of tests run with tox.
Also, switch the python version in tox, from Python 3.6 to Python 3.8.
> Closes issue #215

- django_comments_xtd/api/serializers.py
- docs/webapi.rst
From version 2.7.0, posting a comment using the REST API failed to
process the honeypot field. This commit resolves the issue. There are
two ways to post comments using the REST API, one consist of providing
the honeypot, timestamp and security_hash fields, and the other consist
of authorizing the request (See the Web API in the docs).
> Fixes issue #229 about REST API post comment failing on honeypot field.

- CHANGELOG.md
- django_comments_xtd/api/serializers.py
- django_comments_xtd/tests/test_api_views.py
This PR resolves issue 250, which reports that using the web API to post a comment with a reply_to field that would break the max_thread_level should not produce an exception but rather a controlled response with an appropriate HTTP code. 
The scenario has been added as a test to `tests/test_api_views.py`.
> Fixes issue #250.

- CHANGELOG.md
- django_comments_xtd/api/serializers.py
- django_comments_xtd/templates/django_comments_xtd/comment_tree.html
- django_comments_xtd/tests/settings.py
- django_comments_xtd/tests/test_serializers.py
- example/comp/settings.py
- example/comp/templates/django_comments_xtd/comment_tree.html
- example/simple/settings.py
In this PR the serializer `ReadCommentSerializer` has been modified to return the `submit_date` corresponding to the timezone active in the settings. When `USE_TZ` is not active `submit_date` will be UTC based.
> Closes #248, API must return submit_date in timezone when enabled.

- django_comments_xtd/conf/defaults.py
- django_comments_xtd/forms.py
- django_comments_xtd/tests/test_forms.py
Hello @danirus 
Here is the new implementation according to your comment in #206
> 206 follow up checkbox default value

- django_comments_xtd/templatetags/comments_xtd.py
Render comments from context_dict first if 'comments' were passed in cvars.
Let's say I don't have name 'comments' in context but I use 'top_comments'. Then I render comments with tag in the template:
{% render_xtdcomment_tree with comments=top_commets %}
This throws error because check is happening only in context but 'top_comments' are in context_dict:
https://github.com/danirus/django-comments-xtd/blob/master/django_comments_xtd/templatetags/comments_xtd.py#L332-L338
> RenderXtdCommentTree - comments from context_dict

- .github/workflows/ci-pipeline.yml
- README.rst
- django_comments_xtd/api/views.py
- pyproject.toml
- setup.py
Using standard REST Framework tools to generate OpenAPI schema leads to the warning
```
$ ./manage.py generateschema > openapi-schema.yml
/Users/sergeyivanychev/.local/share/virtualenvs/school-project-rI8dYCXm/lib/python3.9/site-packages/rest_framework/schemas/openapi.py:49: UserWarning: You have a duplicated operationId in your OpenAPI schema: createFlag
Route: /comments/api/feedback/, Method: post
Route: /comments/api/flag/, Method: post
An operationId has to be unique across your schema. Your schema may not work in other tools.
```
This is caused by two similar API views with the same model names. This PR specifies different suffixes for the generated operation IDs so that there's no naming conflict.
> Customize operation ids

- django_comments_xtd/templates/comments/form.html
Avoid submitting comment twice by clicking too fast on send button.
> Close #284

- django_comments_xtd/views.py
`sent` view throws error when `c` is not passed or get unexpected value for `c`.
> views.sent: handle exceptions and return 400

- django_comments_xtd/api/views.py
- django_comments_xtd/tests/test_api_views.py
In case of custom comment model, right now api views are useless because they don't know about additional fields in this model.
> Add ability to use custom comment model in API views

- django_comments_xtd/forms.py
We shouldn't override the whole form field, we need only change particular attribute(s) of the field. For example in original CommentForm field name has max_length attribute which we are loosing/overriding in current code:
```
self.fields['name'] = forms.CharField(
label=_("Name"),
widget=forms.TextInput(attrs={'placeholder': _('name'),
'class': 'form-control'}))
```
Solution is to change only widget and not whole field:
```
self.fields['name'].widget = forms.TextInput(
attrs={'placeholder': _('name'), 'class': 'form-control'})
```
> fix __init__ in XtdCommentForm to keep origin fields parameters

- django_comments_xtd/models.py
Solution found [here](https://github.com/danirus/django-comments-xtd/issues/318#issuecomment-920229621), I tried it and it works for me as well.
I don't know if something is already being worked on to fix this bug in a different way but maybe as a temporary fix ?
> fixes #318 in Django 3.2

- django_comments_xtd/api/urls.py
- django_comments_xtd/api/views.py
- django_comments_xtd/urls.py
Fixes problems described in #334 
Although I can fix this in my project, I think that using project wise DRF defaults is not something, that should `django-comments-xtd` do, especially if they can break the JavaScript code.
> fix defaults for DRF views

- django_comments_xtd/api/views.py
I realized, that the preview view doesn't work after I added the `override_drf_defaults` parameter to `urls.py`. This fixes it.
> fix preview clashing with new include parameter

- django_comments_xtd/api/views.py
- django_comments_xtd/tests/test_api_views.py
- django_comments_xtd/tests/test_forms.py
- django_comments_xtd/tests/test_get_version.py
- django_comments_xtd/tests/test_models.py
- django_comments_xtd/tests/test_moderation.py
- django_comments_xtd/tests/test_serializers.py
- django_comments_xtd/tests/test_templatetags.py
- django_comments_xtd/tests/test_views.py
- pyproject.toml
- requirements.pip
- requirements_tests.pip
- setup.py
This PR:
* Updates version of required dependencies.
* Removes dependency on the **mock** package, as it's already part of the **unittest** Python 3 standard lib package.
* Updates content of `pyproject.toml` file.
> Remove mock dependency

- django_comments_xtd/models.py
- docs/extending.rst
- example/comp/templatetags/comp_filters.py
- example/custom/mycomments/admin.py
- example/custom/mycomments/forms.py
Changed all the ugettext_lazy with gettext_lazy for compatibility with [Django 4.0](https://docs.djangoproject.com/en/4.0/releases/4.0/)
as far as I know this is the only problem preventing to use it fully with the latest update of Django
> ugettext_lazy > gettext_lazy (for Django 4.0)

- django_comments_xtd/api/frontend.py
I am using the `commentbox_props()` function in my app to create my own comment view.
I wanted to restrict the queryset in this function to show correct number of comments (not counting comments private to user).
With this slight change of the `commentbox_props()` function into classmethods I am able to do this without need of copying of the entire code of the function.
> refactor commentbox_props() into classmethod to allow better overriding

- django_comments_xtd/moderation.py
- django_comments_xtd/views.py
> fix: enable content_object in followup email notification context

- django_comments_xtd/locale/de/LC_MESSAGES/django.po
- django_comments_xtd/locale/es/LC_MESSAGES/django.po
- django_comments_xtd/locale/fi/LC_MESSAGES/django.po
- django_comments_xtd/locale/fr/LC_MESSAGES/django.po
- django_comments_xtd/locale/it/LC_MESSAGES/django.po
- django_comments_xtd/locale/nl/LC_MESSAGES/django.po
- django_comments_xtd/locale/no/LC_MESSAGES/django.po
- django_comments_xtd/locale/ru/LC_MESSAGES/django.po
- django_comments_xtd/locale/zh_Hans/LC_MESSAGES/django.po
- django_comments_xtd/templates/404.html
- django_comments_xtd/templates/comments/comment_notification_email.txt
- django_comments_xtd/templates/comments/delete.html
- django_comments_xtd/templates/comments/posted.html
- django_comments_xtd/templates/django_comments_xtd/comment_list.html
- django_comments_xtd/templates/django_comments_xtd/email_confirmation_request.html
- django_comments_xtd/templates/django_comments_xtd/email_confirmation_request.txt
- django_comments_xtd/templates/django_comments_xtd/email_followup_comment.html
- django_comments_xtd/templates/django_comments_xtd/email_followup_comment.txt
- django_comments_xtd/templates/django_comments_xtd/only_users_can_post.html
- django_comments_xtd/templates/django_comments_xtd/removal_notification_email.txt
Many translation calls are missing in the provided templates.
> fix: add missing translation calls

- django_comments_xtd/api/serializers.py
Error happens [here](https://github.com/danirus/django-comments-xtd/blob/master/django_comments_xtd/api/serializers.py#L97). It happens when `apps.get_model(*ctype.split(".", 1))` returns exception other than `AttributeError, TypeError, LookupError`. For example if `ctype="bla"` `*ctype.split(".", 1)` raises `ValueError`. I think in this case makes sense to handle `ValueError` earlier.
> WriteCommentSerializer: local variable 'model' referenced before assignment

- docs/example.rst
- docs/i18n.rst
- docs/javascript.rst
- docs/logic.rst
- docs/migrating.rst
- docs/quickstart.rst
- docs/settings.rst
- docs/templates.rst
- docs/templatetags.rst
- docs/tutorial.rst
- docs/usecases/only-signed-in-can-comment.rst
- docs/webapi.rst
This PR fixes the code-blocks in the docs.
They were indented, causing Sphinx to interpret them as codeblocks first.
> Fix code-blocks in the docs

- docs/conf.py
- docs/requirements.txt
This PR fixes issue #428, which is about the intersphinx inventory of objects for Django not having the usual links. In this PR I switch to the dev inventory which seems to work as expected.
> Switch Django intersphinx to the dev version

- docs/conf.py
- docs/static/chat-text-fill.svg
I have used this [web site](https://isotropic.co/tool/hex-color-to-css-filter/) to create the CSS filter to apply to the SVG image.
> Fix docs: remove 'v' from version dropdown

- django_comments_xtd/templatetags/comments_xtd.py
- docs/extending.rst
- example/custom/README.md
May remind user  the template overriding order somewhere in documentation.
For example:
1. use the Template filesystem loader to prioritize the extra template loading rather than App dirs
```python
TEMPLATES = [
{
"BACKEND": "django.template.backends.django.DjangoTemplates",
"DIRS": [
BASE_DIR / "base" / "templates",  # base/ is not an app, extra dir for FileSystemTemplate
],
},
]
```
2. Mind the app load order which decide the template loaded
```python
INSTALLED_APPS=
[
'myblog', # go before
'django_comments_xtd'
]
INSTALLED_APPS=
[
'django_comments_xtd',
'myblog', # go before
]
```
Refer to django-contrib-comments, https://github.com/django/django-contrib-comments/blob/2.2.0/django_comments/templatetags/comments.py#L184
if the app specific template search is supported, it would be …
> Fix typo in documentation

- .github/workflows/ci-pipeline.yml
- conftest.py
- django_comments_xtd/api/frontend.py
- django_comments_xtd/api/serializers.py
- django_comments_xtd/api/views.py
- django_comments_xtd/tests/pytest_fixtures.py
- django_comments_xtd/tests/test_serializers.py
- django_comments_xtd/tests/test_utils.py
- django_comments_xtd/utils.py
- django_comments_xtd/views.py
- docs/conf.py
- pyproject.toml
- tox.ini
This PR fixes issue #458.
* Rewrite two f-strings that wouldn't otherwise be compatible with Python 3.10 (initial version of Python with which this package promises to be compatible with).
* Add a couple of tests to cover it.
* Include Python 3.10 in the GitHub Actions matrix.
* Fixes the code of `utils.get_app_model_options`, add tests.
> fix issue-458
