django_comments_xtd/models.py

Nesting level in your code can be no more than 3. Fixed, now level can be unlimited.

Tree level unlimited

---

README.rst

It would be very helpful to have the dependencies listed explicitly.

Add dependencies to readme file

---

docs/settings.rst

COMMENTS_XTD_MAX_THREAD_LEVEL and COMMENTS_XTD_MAX_THREAD_LEVEL_BY_APP_MODEL were wrong.

Update MAX_THREAD_LEVEL settings names

---

.travis.yml

Debug KeyError

---

django_comments_xtd/locale/no/LC_MESSAGES/django.po
django_comments_xtd/locale/no/LC_MESSAGES/djangojs.po
example/comp/settings.py

Add Norwegian translations

---

django_comments_xtd/api/frontend.py
docs/javascript.rst
docs/tutorial.rst
example/comp/templates/articles/article_detail.html

Fixes #156 
Replaced `poll_interval` with `polling_interval` at required places

Fixed invalid prop name poll_interval

---

django_comments_xtd/locale/nl/LC_MESSAGES/django.po
pyproject.toml

Hi @danirus,
I added Dutch translations for this project. Would you be so kind to verify and merge this and make a new release?
Thanks in advance!

Add Dutch translations

---

django_comments_xtd/api/serializers.py
django_comments_xtd/templates/404.html
django_comments_xtd/tests/test_views.py
django_comments_xtd/views.py

Fixes issue #80.

---

docs/settings.rst

Added documentation for new 'COMMENTS_XTD_DEFAULT_FOLLOWUP' setting

---

django_comments_xtd/locale/it/LC_MESSAGES/django.po
django_comments_xtd/locale/it/LC_MESSAGES/djangojs.po
docs/i18n.rst
example/comp/settings.py

Hi @danirus,
I added Italian translations for this project. Would you be so kind to verify and merge this in next release?
Thanks in advance!

Add Italian translations

---

.github/workflows/ci-pipeline.yml
django_comments_xtd/api/frontend.py
django_comments_xtd/conf/defaults.py
django_comments_xtd/static/django_comments_xtd/js/src/comment.jsx
django_comments_xtd/static/django_comments_xtd/js/src/commentbox.jsx
django_comments_xtd/static/django_comments_xtd/js/src/commentform.jsx

JS plugin `props.default_followup` = `settings.COMMENTS_XTD_DEFAULT_FOLLOWUP`.

Close #291

---

django_comments_xtd/models.py
django_comments_xtd/tests/settings.py
django_comments_xtd/tests/test_models.py
django_comments_xtd/tests/test_views.py

Fixes issue-311: Correctly update nested_count comment's attribute.

---

django_comments_xtd/api/serializers.py

Fix typo ObjectDoesNotExist -> DoesNotExist

fix typo: ObjectDoesNotExist -> DoesNotExist

---

django_comments_xtd/locale/zh_Hans/LC_MESSAGES/django.po
django_comments_xtd/locale/zh_Hans/LC_MESSAGES/djangojs.po

Hello @danirus,
I added Simplified Chinese translations for this project. Could you review it?
Thanks in advance!

Add Simplified Chinese translations

---

django_comments_xtd/api/serializers.py
django_comments_xtd/tests/test_serializers.py
docs/webapi.rst

Fix issue 407: make proper use of DATETIME_FORMAT

---

django_comments_xtd/api/views.py

This is only ordering added to API which is extracted from #364. It didn't seem to be problem on that PR, so I hope this could be merged while the rest needs discussion.

add ordering filter to the API

---

CHANGELOG.md
README.rst
django_comments_xtd/__init__.py
docs/conf.py
docs/tutorial.rst
example/comp/urls.py
example/custom/urls.py
example/simple/urls.py

This PR:
* Removes unused import.
* Includes small fixes in the documentation.

Latest comment feed

---

docs/conf.py
docs/requirements.txt

This PR is just about updating the docs to sphinx-nefertiti 0.7.0.

Update docs to sphinx-nefertiti 0.7.0

---

CHANGELOG.md
django_comments_xtd/views.py

Closes #447 (remove duplicated code).

Closes #447

---

CHANGELOG.md
docs/quickstart.rst
docs/templates.rst
docs/tutorial.rst

As requested in [PR 446](https://github.com/danirus/django-comments-xtd/pull/446).

Improve docs

---

CHANGELOG.md
django_comments_xtd/__init__.py
docs/conf.py
docs/javascript.rst
docs/tutorial.rst
example/comp/templates/articles/article_detail.html
package.json

Prepare rel 2.10.6
